target("labyrinth-UI")
	set_kind("binary")
	set_languages("c++23")
	add_deps("testkit", "common","debug_utils")
	add_files("./src/*.cpp")
	add_files("./test/*.cpp")
	add_includedirs("./include", {public = true})